# Generated by Django 6.0.6 on 2026-06-15 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crop',
            old_name='pirce_per_kg',
            new_name='price_per_kg',
        ),
    ]
